### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CliCk#2]
Please add a README.md on the root of the project, to briefly explain how the app works.

- **Important**: add login instructions
- Screenshots are welcomed
- Add the link to a live version of the app, if any.

**Comment by caledeito** [comment]
I will add this images
![homepage](https://user-images.githubusercontent.com/32071980/33380109-48ac475e-d51a-11e7-8e32-84bcfe5c83d8.png)
![login](https://user-images.githubusercontent.com/32071980/33380110-48cb74ee-d51a-11e7-98e0-ebd244d36578.png)
![newevent](https://user-images.githubusercontent.com/32071980/33380115-4923afd8-d51a-11e7-8543-47cc4bc66fda.png)

**Comment by wbigger** [comment]
Instructions for login are missing (e.g. username and password to access). Please add them to the README. Reopening issue.

**Comment by caledeito** [comment]
Insert email & psw. Issue close.
