### ISSUE TITLE
Improve appearance of forgot your password page

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CliCk#3]
In the forgot your password page, there are several minor issue to fix for a better UX.

- [x] there is an unnecessary link to the same page (see attachment).
- [x] when user type a wrong password, error message is not red as in the login page
- [x] when user type a wrong password, error message is a link, why?
- [x] when user type a wrong password, error message is not clear, what is a valid email? do you mean that the email do not belong to a known user?

<img width="455" alt="screen shot 2017-11-29 at 10 35 26 am" src="https://user-images.githubusercontent.com/3594326/33368194-48426bbe-d4f1-11e7-9c2e-e3fea299ff82.png">

**Comment by ado-ado** [comment]
Fixed all the issues
