### ISSUE TITLE
Fix month label in homepage

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CliCk#5]
After creating a new event, the month label (JAN, FEB, MAR, ...) on the homepage is not properly displayed.

**Comment by alchemicas** [comment]
That was because of input type="date", my browser didn't support it at the time and I didn't notice the format change when I upgraded to firefox 58.

The fix is in the commit: 4e4fa07c9b8a208181435707db3388108c05a5c4
Files: events-list.component.html events-list.component.ts
